# Generated by Django 4.0.10 on 2024-04-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0002_rename_users_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perevaladded',
            old_name='users',
            new_name='user',
        ),
    ]
