# Generated by Django 4.0.10 on 2024-04-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0004_alter_coord_latitude_alter_coord_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevalimages',
            name='img',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
