# Generated by Django 4.0.10 on 2024-04-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0005_alter_perevalimages_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coord',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coord',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='beauty_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='connect',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='other_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='perevalimages',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='fam',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='otc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
