# Generated by Django 4.0.10 on 2024-04-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
